### ISSUE TITLE
需要一份部署文档

### ISSUE THREAD

**Issue by airsmon** [JCIOTeam/ISSUE#1]
问题描述
1.镜像构建后，需要将public内容部署到caddy服务中吗？运行yarn run serve，访问空白（很多JS 404）
2.file browser样式没有提供，默认使用caddy提供的file browser？
3./api/mirrors信息是通过[MirrorsDotNet](https://github.com/ZJUSCT/MirrorsDotNet)项目获取的吗？

**Comment by zyh001** [comment]
@airsmon 
> 1.镜像构建后，需要将public内容部署到caddy服务中吗？运行yarn run serve，访问空白（很多JS 404）

在您构建之后，您需要将 `/caddy` 作为您 Web Server 的 root 目录，目录中有供参考的 `Caddyfile` 配置文件

> 2.file browser样式没有提供，默认使用caddy提供的file browser？

目前我站 File Browser 页面仍在开发中，目前暂未开源

> 3./api/mirrors信息是通过[MirrorsDotNet](https://github.com/ZJUSCT/MirrorsDotNet)项目获取的吗？

是的，您需要部署 MirrorsDotNet 作为您的镜像管理工具
